parameter:
  size:
    transaction: 200
    parallel: 15
    batch: 4
    proportion: "5:5:5"
  structure:
    schema: test
    table: LTEST1
    content: int,string
    length: 0,10
  update:
    where: 1
    whereColumnName: ID0
    set: 2
    setColumnName: ID1
spring:
  datasource:
    url: "jdbc:mysql://192.168.124.134:3306/"
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
