parameter:
  name: "App"
  size:
    transaction: 100
    parallel: 15
    batch: 4
    proportion: "5:5:5"
  pool:
    corePoolSize: ${parameter.size.parallel}
    maximumPoolSize: 64
    keepAliveTime: 60
    blockingQueue: 64
  structure:
    schema: test
    table: LTEST1
    content: int,string
    length: 0,10
  update:
    where: 1
    whereColumnName: ID0
    set: 2
    setColumnName: ID1
  report:
    path: "./报告.md"
spring:
  profiles:
    active: dev
  main:
    banner-mode: off
  datasource:
    url: "jdbc:mysql://192.168.124.134:3306/"
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
---
spring:
  config:
    activate:
      on-profile: test
logging:
  config: classpath:logging-config.xml
---
spring:
  config:
    activate:
      on-profile: dev
logging:
  level:
    com.sics.tool: info
    com.sics.tool.task.AbstractTask: debug
    org.springframework: info
  file:
    name: logs/${parameter.name}.log
  logback:
    rolling policy:
      max-file-size: 50MB
      file-name-pattern: logs/%d{yyyy-MM}/info.%d{yyyy-MM-dd}.%i.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%t] [%p] %c{1.1.~.~} - %m%n"
